name: Build and deploy Python app to Azure Web App - vectorindex-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # (VALGFRITT) Kjør en kjapp sjekk / tester uten venv
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (for lint / tester, ikke for deploy)
        run: |
          pip install -r requirements.txt

      # - name: Run tests
      #   run: pytest  # hvis du har tester

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'vectorindex-server'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A38891A383C04815B56CCDBE52DCFADC }}
